import { IsString, IsDate, IsOptional, IsBoolean, IsArray, ValidateNested, IsNumber } from 'class-validator';
import { Type } from 'class-transformer';

export class JournalLineDto {
  @IsString()
  accountId: string;

  @IsString()
  @IsOptional()
  description?: string;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  debit?: number;

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  credit?: number;
}

export class CreateJournalEntryDto {
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  date?: Date;

  @IsString()
  @IsOptional()
  reference?: string;

  @IsString()
  description: string;

  @IsString()
  @IsOptional()
  outletId?: string;

  @IsString()
  @IsOptional()
  createdById?: string;

  @IsBoolean()
  @IsOptional()
  isAutoGenerated?: boolean;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => JournalLineDto)
  lines: JournalLineDto[];
}
